name: Build Jekyll Site

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout (GitHub)
      uses: actions/checkout@v3

    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:    
        push: never
        runCmd: make ci-build
